# Generated by Django 4.1.5 on 2023-01-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_description',
            new_name='description',
        ),
    ]
